### ISSUE TITLE
Strange behavior on an HTTPS service

### ISSUE THREAD

**Issue by medovs** [NX211/traefik-proxmox-provider#14]
Hi everyone,
I'm encountering an issue with the following configuration:
```
traefik.enable=true
traefik.http.routers.deluge-lan.rule=Host(`deluge.local.presta-news.fr`) && ClientIP(`192.168.2.0/24`)
traefik.http.routers.deluge-lan.service=deluge
traefik.http.routers.deluge.rule=Host(`deluge.local.presta-news.fr`)
traefik.http.routers.deluge.service=deluge
traefik.http.routers.deluge.middlewares=wan-auth@file
traefik.http.services.deluge.loadbalancer.server.url=https://192.168.2.81:8112
traefik.http.services.deluge.loadbalancer.server.passHostHeader=true
traefik.http.services.deluge.loadbalancer.server.serversTransport=insecure-transport
```
When I access the URL, it responds with "Internal Server Error".
Log
```
{
    "ClientAddr": "130.93.53.251:55419",
    "ClientHost": "130.93.53.251",
    "ClientPort": "55419",
    "ClientUsername": "-",
    "DownstreamContentSize": 21,
    "DownstreamStatus": 500,
    "Duration": 2684175,
    "OriginContentSize": 21,
    "OriginDuration": 2241348,
    "OriginStatus": 500,
    "Overhead": 442827,
    "RequestAddr": "deluge.local.presta-news.fr",
    "RequestContentSize": 0,
    "RequestCount": 3582,
    "RequestHost": "deluge.local.presta-news.fr",
    "RequestMethod": "GET",
    "RequestPath": "/",
    "RequestPort": "-",
    "RequestProtocol": "HTTP/2.0",
    "RequestScheme": "https",
    "RetryAttempts": 0,
    "RouterName": "https-deluge@plugin-traefik-proxmox-provider",
    "ServiceAddr": "192.168.2.81:8112",
    "ServiceName": "deluge@plugin-traefik-proxmox-provider",
    "ServiceURL": "https://192.168.2.81:8112",
    "SpanId": "0000000000000000",
    "StartLocal": "2025-04-09T10:53:06.375800547+02:00",
    "StartUTC": "2025-04-09T08:53:06.375800547Z",
    "TLSCipher": "TLS_AES_128_GCM_SHA256",
    "TLSVersion": "1.3",
    "TraceId": "00000000000000000000000000000000",
    "entryPointName": "https",
    "level": "info",
    "msg": "",
    "request_User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36",
    "time": "2025-04-09T10:53:06+02:00"
}
```
However, if I configure it using a file like this:
```
http:
  routers:
    deluge-lan:
      rule: "Host(`deluge.local.presta-news.fr`) && ClientIP(`192.168.2.0/24`)"
      service: deluge
    deluge:
      rule: "Host(`deluge.local.presta-news.fr`)"
      service: deluge
      middlewares:
        - wan-auth

  services:
    deluge:
      loadBalancer:
        servers:
          - url: "https://192.168.2.81:8112"
        passHostHeader: true
        serversTransport: "insecure-transport"
```
I can access the URL without any error.
Log
```
{
    "ClientAddr": "130.93.53.251:55547",
    "ClientHost": "130.93.53.251",
    "ClientPort": "55547",
    "ClientUsername": "-",
    "DownstreamContentSize": 2683,
    "DownstreamStatus": 200,
    "Duration": 5711672,
    "OriginContentSize": 2683,
    "OriginDuration": 5295948,
    "OriginStatus": 200,
    "Overhead": 415724,
    "RequestAddr": "deluge.local.presta-news.fr",
    "RequestContentSize": 0,
    "RequestCount": 3856,
    "RequestHost": "deluge.local.presta-news.fr",
    "RequestMethod": "GET",
    "RequestPath": "/",
    "RequestPort": "-",
    "RequestProtocol": "HTTP/2.0",
    "RequestScheme": "https",
    "RetryAttempts": 0,
    "RouterName": "https-deluge@file",
    "ServiceAddr": "192.168.2.81:8112",
    "ServiceName": "deluge@file",
    "ServiceURL": "https://192.168.2.81:8112",
    "SpanId": "0000000000000000",
    "StartLocal": "2025-04-09T10:56:55.414137034+02:00",
    "StartUTC": "2025-04-09T08:56:55.414137034Z",
    "TLSCipher": "TLS_AES_128_GCM_SHA256",
    "TLSVersion": "1.3",
    "TraceId": "00000000000000000000000000000000",
    "entryPointName": "https",
    "level": "info",
    "msg": "",
    "request_User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36",
    "time": "2025-04-09T10:56:55+02:00"
}
```
Can you help me find the mistake that slipped in and is still hiding from me?

Thanks!
