### ISSUE TITLE
Disable error spam logs

### ISSUE THREAD

**Issue by userXinos** [NX211/traefik-proxmox-provider#15]
The log is full of errors from this plugin.
field `apiLogging` removed from config

**Comment by NX211** [comment]
Hey,

Thanks for opening the issue. Are you still having this issue ?

**Comment by userXinos** [comment]
nope

traefik.yaml:
```yaml
providers:
  plugin:
    proxmox:
      apiEndpoint: "https://proxmox-ve"
      apiTokenId: "admin@cloudbrew!traefik"
      apiToken: "2cb4814c-4802-438c-b48c-0a4ee6bb24fd"
      apiValidateSSL: false

experimental:
  otlpLogs: true
  plugins:
    proxmox:
      moduleName: github.com/NX211/traefik-proxmox-provider
      version: v0.7.6
```

<img width="2215" height="939" alt="Image" src="https://github.com/user-attachments/assets/8d5afaa8-b47c-4869-8b08-5170dc204508" />

**Comment by simensgreen** [comment]
Me too. Scanning container shown as error but permission check failed is debug. seems typo log level in logger

**Comment by simensgreen** [comment]
Seems like unconditional `log.Printf` in many places, like https://github.com/NX211/traefik-proxmox-provider/blob/0ece44f2f22ddbc70a50bc0d996cb9b9ec4df22a/provider/provider.go#L273

**Comment by NX211** [comment]
My apologies everyone for my long absence. Unfortunately, the motherboard in my Proxmox server died and I haven't had the space to fix it. So I have obviously been neglecting the project and am happy to accept pull request but I can't test or anything at the moment.

**Comment by userXinos** [comment]
nothing happened. 

I migrated directly to git to make sure I was using the latest local version.

```sh
/configs/traefik/plugins/src/github.com/NX211/traefik-proxmox-provider$ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

```yml
log:
  level: "INFO"
  format: genericCLF

providers:
  plugin:
    proxmox:
      apiEndpoint: "https://proxmox-ve.local"
      apiTokenId: "admin@pve!traefik"
      apiToken: "yes"
      apiValidateSSL: false

experimental:
  otlpLogs: true
  localPlugins:
    proxmox:
      moduleName: github.com/NX211/traefik-proxmox-provider
```

~1k posts per hour 

<img width="2764" height="1227" alt="Image" src="https://github.com/user-attachments/assets/1170f549-b513-4ee5-8b6b-8c8b31df91fc" />
