### ISSUE TITLE
Traefik - failed to build provider - undefined: traefik_proxmox_provider

### ISSUE THREAD

**Issue by medovs** [NX211/traefik-proxmox-provider#7]
Hello,

I get this error :
```
{"level":"info","plugins":["traefik-proxmox-provider"],"time":"2025-03-27T08:56:10+01:00","message":"Loading plugins..."}
{"level":"info","plugins":["traefik-proxmox-provider"],"time":"2025-03-27T08:56:10+01:00","message":"Plugins loaded."}
{"level":"error","error":"command traefik error: plugin: failed to build provider: unknown plugin type: apiTokenId","time":"2025-03-27T08:56:10+01:00","message":"Command error"}
```

My config
Traefik 3.3.4
/etc/traefik/traefik.yaml
```
experimental:
  plugins:
    traefik-proxmox-provider:
      moduleName: "github.com/NX211/traefik-proxmox-provider"
      version: "v0.4.0"

providers:
  file:
    directory: /etc/traefik/conf.d/
  plugin:
      traefik-proxmox-provider:
      apiEndpoint: "https://192.168.x.xxx:8006"
      apiLogging: info
      apiToken: "xxxxxxx-xxxxxxx-xxxx-xxxxx-xxxxxxxx"
      apiTokenId: "root@pam!traefik"
      apiValidateSSL: "true"
      pollInterval: 5s

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: letsencrypt
  traefik:
    address: ':8080'
```

Can you help me?
